<template>
    <div class="addresses-registration-section">
      <div class="title-container">
        <h1>Registro de barrios</h1>
        <router-link :to="{ name: 'AdminStreetLayout' }">
          <button class="back-btn" type="button">Volver a la lista</button>
        </router-link>
      </div>
      <div class="form-container">
          <form action="#">
            <div class="info-field dep-city-field">
              <label for="department">Departamento: </label>
              <select
                class="form-select form-select-sm city-selector"
                id="department"
                name="department"
                v-model="selectedDepartment"
                @change="updateCities"
              >
                <option value="">Selecciona tu departamento</option>
                <option v-for="dep in departments" :key="dep.id" :value="dep.id">
                  {{ dep.name }}
                </option>
              </select>
              <label for="city">Ciudad: </label>
              <select
                class="form-select form-select-sm city-selector"
                id="city"
                name="city"
                v-model="selectedCity"
              >
                <option value="">Selecciona tu ciudad</option>
                <option v-for="city in filteredCities" :key="city">{{ city }}</option>
              </select>
            </div>
            <div class="info-field">
              <label for="street-name">Nombre del Barrio: </label>
              <input id="street-name" type="text" placeholder="Los Olmos" >
            </div>
            <div class="info-field">
              <label for="street-address">Dirección: </label>
              <input id="street-address" type="text" placeholder="Cra. 16 #1524" >
            </div>
            <div class="info-field">
              <label for="street-address">Código postal: </label>
              <input id="street-address" type="number" placeholder="250251" >
            </div>
            <div class="info-field">
              <div class="map-container">
                <h2>Selecciona tu ubicación:</h2>
                <div @click="getLatLong" class="map" id="map"></div>
              </div>
              <div class="long-lat-container">
                <input
                  v-model="latitude"
                  placeholder="Latitud"
                  class="form-control location-input"
                  type="number"
                  id="latitude"
                  name="latitude"
                  disabled
                >
                <input
                  v-model="longitude"
                  placeholder="Longitud"
                  class="form-control location-input"
                  type="number"
                  id="longitude"
                  name="longitude"
                  disabled
                >
              </div>
            </div>
            <div class="button-field">
              <button class="street-submit-btn" type="submit">Registrar</button>
            </div>
          </form>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue'
  import 'leaflet/dist/leaflet.css'
  import * as L from 'leaflet'

  const initialMap = ref(null)
  const latitude = ref(null)
  const longitude = ref(null)
  const currentMarker = ref(null)
  
  const departments = ref([
    { id: 1, name: 'Amazonas' },
    { id: 2, name: 'Antioquia' },
    { id: 3, name: 'Arauca' },
    { id: 4, name: 'Atlántico' },
    { id: 5, name: 'Bolívar' },
    { id: 6, name: 'Boyacá' },
    { id: 7, name: 'Caldas' },
    { id: 8, name: 'Caquetá' },
    { id: 9, name: 'Casanare' },
    { id: 10, name: 'Cauca' },
    { id: 11, name: 'Cesar' },
    { id: 12, name: 'Chocó' },
    { id: 13, name: 'Córdoba' },
    { id: 14, name: 'Cundinamarca' },
    { id: 15, name: 'Guainía' },
    { id: 16, name: 'Guaviare' },
    { id: 17, name: 'Huila' },
    { id: 18, name: 'La Guajira' },
    { id: 19, name: 'Magdalena' },
    { id: 20, name: 'Meta' },
    { id: 21, name: 'Nariño' },
    { id: 22, name: 'Norte de Santander' },
    { id: 23, name: 'Putumayo' },
    { id: 24, name: 'Quindío' },
    { id: 25, name: 'Risaralda' },
    { id: 26, name: 'San Andrés y Providencia' },
    { id: 27, name: 'Santander' },
    { id: 28, name: 'Sucre' },
    { id: 29, name: 'Tolima' },
    { id: 30, name: 'Valle del Cauca' },
    { id: 31, name: 'Vaupés' },
    { id: 32, name: 'Vichada' }
  ])
  
  const cities = ref([
    { departmentId: 1, names: ['Leticia', 'Puerto Nariño'] },
    {
      departmentId: 2,
      names: [
        'Abejorral',
        'Abriaquí',
        'Alejandría',
        'Amagá',
        'Amalfi',
        'Andes',
        'Angelópolis',
        'Angostura',
        'Anorí',
        'Anzá',
        'Apartadó',
        'Arboletes',
        'Argelia',
        'Armenia',
        'Barbosa',
        'Bello',
        'Belmira',
        'Betania',
        'Betulia',
        'Briceño',
        'Buriticá',
        'Cáceres',
        'Caicedo',
        'Caldas',
        'Campamento',
        'Cañasgordas',
        'Caracolí',
        'Caramanta',
        'Carepa',
        'Carolina del Príncipe',
        'Caucasia',
        'Chigorodó',
        'Cisneros',
        'Ciudad Bolívar',
        'Cocorná',
        'Concepción',
        'Concordia',
        'Copacabana',
        'Dabeiba',
        'Donmatías',
        'Ebéjico',
        'El Bagre',
        'Entrerríos',
        'Envigado',
        'Fredonia',
        'Frontino',
        'Giraldo',
        'Girardota',
        'Gómez Plata',
        'Granada',
        'Guadalupe',
        'Guarne',
        'Guatapé',
        'Heliconia',
        'Hispania',
        'Itagüí',
        'Ituango',
        'Jardín',
        'Jericó',
        'La Ceja',
        'La Estrella',
        'La Pintada',
        'La Unión',
        'Liborina',
        'Maceo',
        'Marinilla',
        'Medellín',
        'Montebello',
        'Murindó',
        'Mutatá',
        'Nariño',
        'Nechí',
        'Necoclí',
        'Olaya',
        'Peque',
        'Pueblorrico',
        'Puerto Berrío',
        'Puerto Nare',
        'Puerto Triunfo',
        'Remedios',
        'Retiro',
        'Rionegro',
        'Sabanalarga',
        'Sabaneta',
        'Salgar',
        'San Andrés de Cuerquía',
        'San Carlos',
        'San Francisco',
        'San Jerónimo',
        'San José de la Montaña',
        'San Juan de Urabá',
        'San Luis',
        'San Pedro de Urabá',
        'San Pedro de los Milagros',
        'San Rafael',
        'San Roque',
        'San Vicente Ferrer',
        'Santa Bárbara',
        'Santa Fé de Antioquia',
        'Santa Rosa de Osos',
        'Santo Domingo',
        'El Santuario',
        'Segovia',
        'Sonsón',
        'Sopetrán',
        'Támesis',
        'Tarazá',
        'Tarso',
        'Titiribí',
        'Toledo',
        'Turbo',
        'Uramita',
        'Urrao',
        'Valdivia',
        'Valparaíso',
        'Vegachí',
        'Venecia',
        'Vigía del Fuerte',
        'Yalí',
        'Yarumal',
        'Yolombó',
        'Yondó',
        'Zaragoza'
      ]
    },
    {
      departmentId: 3,
      names: ['Arauca', 'Arauquita', 'Cravo Norte', 'Fortul', 'Puerto Rondón', 'Saravena', 'Tame']
    },
    {
      departmentId: 4,
      names: [
        'Baranoa',
        'Barranquilla',
        'Campo de la Cruz',
        'Candelaria',
        'Galapa',
        'Juan de Acosta',
        'Luruaco',
        'Malambo',
        'Manatí',
        'Palmar de Varela',
        'Piojó',
        'Polonuevo',
        'Ponedera',
        'Puerto Colombia',
        'Repelón',
        'Sabanagrande',
        'Sabanalarga',
        'Santa Lucía',
        'Santo Tomás',
        'Soledad',
        'Suan',
        'Tubará',
        'Usiacurí'
      ]
    },
    {
      departmentId: 5,
      names: [
        'Achí',
        'Altos del Rosario',
        'Arenal',
        'Arjona',
        'Arroyohondo',
        'Barranco de Loba',
        'Calamar',
        'Cantagallo',
        'Cartagena de Indias',
        'Cicuco',
        'Clemencia',
        'Córdoba',
        'El Carmen de Bolívar',
        'El Guamo',
        'El Peñón',
        'Hatillo de Loba',
        'Magangué',
        'Mahates',
        'Margarita',
        'María la Baja',
        'Mompós',
        'Montecristo',
        'Morales',
        'Norosí',
        'Pinillos',
        'Regidor',
        'Río Viejo',
        'San Cristóbal',
        'San Estanislao',
        'San Fernando',
        'San Jacinto del Cauca',
        'San Jacinto',
        'San Juan Nepomuceno',
        'San Martín de Loba',
        'San Pablo',
        'Santa Catalina',
        'Santa Rosa',
        'Santa Rosa del Sur',
        'Simití',
        'Soplaviento',
        'Talaigua Nuevo',
        'Tiquisio',
        'Turbaco',
        'Turbaná',
        'Villanueva',
        'Zambrano'
      ]
    },
    {
      departmentId: 6,
      names: [
        'Almeida',
        'Aquitania',
        'Arcabuco',
        'Belén',
        'Berbeo',
        'Betéitiva',
        'Boavita',
        'Boyacá',
        'Briceño',
        'Buenavista',
        'Busbanzá',
        'Caldas',
        'Campohermoso',
        'Cerinza',
        'Chinavita',
        'Chiquinquirá',
        'Chíquiza',
        'Chiscas',
        'Chita',
        'Chitaraque',
        'Chivatá',
        'Ciénega',
        'Cómbita',
        'Coper',
        'Corrales',
        'Covarachía',
        'Cubará',
        'Cucaita',
        'Cuítiva',
        'Chíquiza',
        'El Cocuy',
        'El Espino',
        'Firavitoba',
        'Floresta',
        'Gachantivá',
        'Gameza',
        'Garagoa',
        'Guacamayas',
        'Guateque',
        'Guayatá',
        'Güicán',
        'Iza',
        'Jenesano',
        'Jericó',
        'La Capilla',
        'La Uvita',
        'La Victoria',
        'Labranzagrande',
        'Macanal',
        'Maripí',
        'Miraflores',
        'Mongua',
        'Monguí',
        'Moniquirá',
        'Motavita',
        'Muzo',
        'Nobsa',
        'Nuevo Colón',
        'Oicatá',
        'Otanche',
        'Pachavita',
        'Páez',
        'Paipa',
        'Pajarito',
        'Panqueba',
        'Pauna',
        'Paya',
        'Paz del Río',
        'Pesca',
        'Pisba',
        'Puerto Boyacá',
        'Quípama',
        'Ramiriquí',
        'Ráquira',
        'Rondón',
        'Saboyá',
        'Sáchica',
        'Samacá',
        'San Eduardo',
        'San José de Pare',
        'San Luis de Gaceno',
        'San Mateo',
        'San Miguel de Sema',
        'San Pablo de Borbur',
        'Santa María',
        'Santa Rosa de Viterbo',
        'Santa Sofía',
        'Santana',
        'Sativanorte',
        'Sativasur',
        'Siachoque',
        'Soatá',
        'Socha',
        'Socotá',
        'Sogamoso',
        'Somondoco',
        'Sora',
        'Soracá',
        'Sotaquirá',
        'Susacón',
        'Sutamarchán',
        'Sutatenza',
        'Tasco',
        'Tenza',
        'Tibaná',
        'Tibasosa',
        'Tinjacá',
        'Tipacoque',
        'Toca',
        'Togüí',
        'Tópaga',
        'Tota',
        'Tunja',
        'Tununguá',
        'Turmequé',
        'Tuta',
        'Tutazá',
        'Úmbita',
        'Ventaquemada',
        'Viracachá',
        'Zetaquira'
      ]
    },
    {
      departmentId: 7,
      names: [
        'Aguadas',
        'Anserma',
        'Aranzazu',
        'Belalcázar',
        'Chinchiná',
        'Filadelfia',
        'La Dorada',
        'La Merced',
        'Manizales',
        'Manzanares',
        'Marmato',
        'Marquetalia',
        'Marulanda',
        'Neira',
        'Norcasia',
        'Pácora',
        'Palestina',
        'Pensilvania',
        'Riosucio',
        'Risaralda',
        'Salamina',
        'Samaná',
        'San José',
        'Supía',
        'Victoria',
        'Villamaría',
        'Viterbo'
      ]
    },
    {
      departmentId: 8,
      names: [
        'Albania',
        'Belén de los Andaquíes',
        'Cartagena del Chairá',
        'Curillo',
        'El Doncello',
        'El Paujil',
        'Florencia',
        'La Montañita',
        'Milán',
        'Morelia',
        'Puerto Rico',
        'San José del Fragua',
        'San Vicente del Caguán',
        'Solano',
        'Solita',
        'Valparaíso'
      ]
    },
    {
      departmentId: 9,
      names: [
        'Aguazul',
        'Chameza',
        'Hato Corozal',
        'La Salina',
        'Maní',
        'Monterrey',
        'Nunchía',
        'Orocué',
        'Paz de Ariporo',
        'Pore',
        'Recetor',
        'Sabanalarga',
        'Sácama',
        'San Luis de Palenque',
        'Támara',
        'Tauramena',
        'Trinidad',
        'Villanueva',
        'Yopal'
      ]
    },
    {
      departmentId: 10,
      names: [
        'Almaguer',
        'Argelia',
        'Balboa',
        'Bolívar',
        'Buenos Aires',
        'Cajibío',
        'Caldono',
        'Caloto',
        'Corinto',
        'El Tambo',
        'Florencia',
        'Guachené',
        'Guapí',
        'Inzá',
        'Jambaló',
        'La Sierra',
        'La Vega',
        'López de Micay',
        'Mercaderes',
        'Miranda',
        'Morales',
        'Padilla',
        'Patía',
        'Piamonte',
        'Piendamó',
        'Popayán',
        'Puerto Tejada',
        'Puracé',
        'Rosas',
        'San Sebastián',
        'Santa Rosa',
        'Santander de Quilichao',
        'Silvia',
        'Sotará',
        'Suárez',
        'Sucre',
        'Timbío',
        'Timbiquí',
        'Toribío',
        'Totoró',
        'Villa Rica'
      ]
    },
    {
      departmentId: 11,
      names: [
        'Aguachica',
        'Agustín Codazzi',
        'Astrea',
        'Becerril',
        'Bosconia',
        'Chimichagua',
        'Chiriguaná',
        'Curumaní',
        'El Copey',
        'El Paso',
        'Gamarra',
        'González',
        'La Gloria',
        'La Jagua de Ibirico',
        'La Paz',
        'Manaure',
        'Pailitas',
        'Pelaya',
        'Pueblo Bello',
        'Río de Oro',
        'San Alberto',
        'San Diego',
        'San Martín',
        'Tamalameque',
        'Valledupar'
      ]
    },
    {
      departmentId: 12,
      names: [
        'Acandí',
        'Alto Baudó',
        'Atrato',
        'Bagadó',
        'Bahía Solano',
        'Bajo Baudó',
        'Bojayá',
        'Cantón de San Pablo',
        'Carmen del Darien',
        'Cértegui',
        'Condoto',
        'El Carmen de Atrato',
        'El Litoral del San Juan',
        'Istmina',
        'Juradó',
        'Lloró',
        'Medio Atrato',
        'Medio Baudó',
        'Medio San Juan',
        'Novita',
        'Nuquí',
        'Quibdó',
        'Río Iro',
        'Río Quito',
        'Riosucio',
        'San José del Palmar',
        'Sipí',
        'Tadó',
        'Unguía',
        'Unión Panamericana'
      ]
    },
    {
      departmentId: 13,
      names: [
        'Ayapel',
        'Buenavista',
        'Canalete',
        'Cereté',
        'Chimá',
        'Chinú',
        'Ciénaga de Oro',
        'Cotorra',
        'La Apartada',
        'Lorica',
        'Los Córdobas',
        'Momil',
        'Montelíbano',
        'Montería',
        'Moñitos',
        'Planeta Rica',
        'Pueblo Nuevo',
        'Puerto Escondido',
        'Puerto Libertador',
        'Purísima',
        'Sahagún',
        'San Andrés Sotavento',
        'San Antero',
        'San Bernardo del Viento',
        'San Carlos',
        'San Pelayo',
        'Tierralta',
        'Tuchín',
        'Valencia'
      ]
    },
    {
      departmentId: 14,
      names: [
        'Agua de Dios',
        'Albán',
        'Anapoima',
        'Anolaima',
        'Arbeláez',
        'Beltrán',
        'Bituima',
        'Bojacá',
        'Cabrera',
        'Cachipay',
        'Cajicá',
        'Caparrapí',
        'Cáqueza',
        'Carmen de Carupa',
        'Chaguaní',
        'Chía',
        'Chipaque',
        'Choachí',
        'Chocontá',
        'Cogua',
        'Cota',
        'Cucunubá',
        'El Colegio',
        'El Peñón',
        'El Rosal',
        'Facatativá',
        'Fómeque',
        'Fosca',
        'Funza',
        'Fúquene',
        'Fusagasugá',
        'Gachalá',
        'Gachancipá',
        'Gachetá',
        'Gama',
        'Girardot',
        'Granada',
        'Guachetá',
        'Guaduas',
        'Guasca',
        'Guataquí',
        'Guatavita',
        'Guayabal de Síquima',
        'Guayabetal',
        'Gutiérrez',
        'Jerusalén',
        'Junín',
        'La Calera',
        'La Mesa',
        'La Palma',
        'La Peña',
        'La Vega',
        'Lenguazaque',
        'Machetá',
        'Madrid',
        'Manta',
        'Medina',
        'Mosquera',
        'Nariño',
        'Nemocón',
        'Nilo',
        'Nimaima',
        'Nocaima',
        'Venecia',
        'Pacho',
        'Paime',
        'Pandi',
        'Paratebueno',
        'Pasca',
        'Puerto Salgar',
        'Pulí',
        'Quebradanegra',
        'Quetame',
        'Quipile',
        'Ricaurte',
        'San Antonio del Tequendama',
        'San Bernardo',
        'San Cayetano',
        'San Francisco',
        'San Juan de Rioseco',
        'Sasaima',
        'Sesquilé',
        'Sibaté',
        'Silvania',
        'Simijaca',
        'Soacha',
        'Sopó',
        'Subachoque',
        'Suesca',
        'Supatá',
        'Susa',
        'Sutatausa',
        'Tabio',
        'Tausa',
        'Tena',
        'Tenjo',
        'Tibacuy',
        'Tibirita',
        'Tocaima',
        'Tocancipá',
        'Topaipí',
        'Ubalá',
        'Ubaque',
        'Ubaté',
        'Une',
        'Útica',
        'Vergara',
        'Vianí',
        'Villagómez',
        'Villapinzón',
        'Villeta',
        'Viotá',
        'Yacopí',
        'Zipacón',
        'Zipaquirá'
      ]
    },
    { departmentId: 15, names: ['Inírida'] },
    { departmentId: 16, names: ['Calamar', 'El Retorno', 'Miraflores', 'San José del Guaviare'] },
    {
      departmentId: 17,
      names: [
        'Acevedo',
        'Agrado',
        'Aipe',
        'Algeciras',
        'Altamira',
        'Baraya',
        'Campoalegre',
        'Colombia',
        'Elías',
        'Garzón',
        'Gigante',
        'Guadalupe',
        'Hobo',
        'Iquira',
        'Isnos',
        'La Argentina',
        'La Plata',
        'Nátaga',
        'Neiva',
        'Oporapa',
        'Paicol',
        'Palermo',
        'Palestina',
        'Pital',
        'Pitalito',
        'Rivera',
        'Saladoblanco',
        'San Agustín',
        'Santa María',
        'Suaza',
        'Tarqui',
        'Tello',
        'Teruel',
        'Tesalia',
        'Timaná',
        'Villavieja',
        'Yaguará'
      ]
    },
    {
      departmentId: 18,
      names: [
        'Albania',
        'Barrancas',
        'Dibulla',
        'Distracción',
        'El Molino',
        'Fonseca',
        'Hatonuevo',
        'La Jagua del Pilar',
        'Maicao',
        'Manaure',
        'Riohacha',
        'San Juan del Cesar',
        'Uribia',
        'Urumita',
        'Villanueva'
      ]
    },
    {
      departmentId: 19,
      names: [
        'Algarrobo',
        'Aracataca',
        'Ariguaní',
        'Cerro San Antonio',
        'Chibolo',
        'Ciénaga',
        'Concordia',
        'El Banco',
        'El Piñón',
        'El Retén',
        'Fundación',
        'Guamal',
        'Nueva Granada',
        'Pedraza',
        'Pijiño del Carmen',
        'Pivijay',
        'Plato',
        'Puebloviejo',
        'Remolino',
        'Sabanas de San Ángel',
        'Salamina',
        'San Sebastián de Buenavista',
        'San Zenón',
        'Santa Ana',
        'Santa Bárbara de Pinto',
        'Santa Marta',
        'Sitionuevo',
        'Tenerife',
        'Zapayán',
        'Zona Bananera'
      ]
    },
    {
      departmentId: 20,
      names: [
        'Acacías',
        'Barranca de Upía',
        'Cabuyaro',
        'Castilla la Nueva',
        'Cubarral',
        'Cumaral',
        'El Calvario',
        'El Castillo',
        'El Dorado',
        'Fuente de Oro',
        'Granada',
        'Guamal',
        'La Macarena',
        'Lejanías',
        'Mapiripán',
        'Mesetas',
        'Puerto Concordia',
        'Puerto Gaitán',
        'Puerto Lleras',
        'Puerto López',
        'Puerto Rico',
        'Restrepo',
        'San Carlos de Guaroa',
        'San Juan de Arama',
        'San Juanito',
        'San Martín',
        'Uribe',
        'Villavicencio',
        'Vistahermosa'
      ]
    },
    {
      departmentId: 21,
      names: [
        'Aldana',
        'Ancuya',
        'Arboleda',
        'Barbacoas',
        'Belén',
        'Buesaco',
        'Chachagüí',
        'Colón',
        'Consacá',
        'Contadero',
        'Córdoba',
        'Cuaspud',
        'Cumbal',
        'Cumbitara',
        'El Charco',
        'El Peñol',
        'El Rosario',
        'El Tablón de Gómez',
        'El Tambo',
        'Francisco Pizarro',
        'Funes',
        'Guachucal',
        'Guaitarilla',
        'Gualmatán',
        'Iles',
        'Imués',
        'Ipiales',
        'La Cruz',
        'La Florida',
        'La Llanada',
        'La Tola',
        'La Unión',
        'Leiva',
        'Linares',
        'Los Andes',
        'Magüí Payán',
        'Mallama',
        'Mosquera',
        'Nariño',
        'Olaya Herrera',
        'Ospina',
        'Pasto',
        'Policarpa',
        'Potosí',
        'Providencia',
        'Puerres',
        'Pupiales',
        'Ricaurte',
        'Roberto Payán',
        'Samaniego',
        'San Bernardo',
        'San Lorenzo',
        'San Pablo',
        'San Pedro de Cartago',
        'Sandoná',
        'Santa Bárbara',
        'Santacruz',
        'Sapuyes',
        'Taminango',
        'Tangua',
        'Tumaco',
        'Túquerres',
        'Yacuanquer'
      ]
    },
    {
      departmentId: 22,
      names: [
        'Abrego',
        'Arboledas',
        'Bochalema',
        'Bucarasica',
        'Cáchira',
        'Cacota',
        'Chinácota',
        'Chitagá',
        'Convención',
        'Cúcuta',
        'Cucutilla',
        'Durania',
        'El Carmen',
        'El Tarra',
        'El Zulia',
        'Gramalote',
        'Hacarí',
        'Herrán',
        'Labateca',
        'La Esperanza',
        'La Playa',
        'Los Patios',
        'Lourdes',
        'Mutiscua',
        'Ocaña',
        'Pamplona',
        'Pamplonita',
        'Puerto Santander',
        'Ragonvalia',
        'Salazar de Las Palmas',
        'San Calixto',
        'San Cayetano',
        'Santiago',
        'Sardinata',
        'Silos',
        'Teorama',
        'Tibú',
        'Toledo',
        'Villa Caro',
        'Villa del Rosario'
      ]
    },
    {
      departmentId: 23,
      names: [
        'Colón',
        'Mocoa',
        'Orito',
        'Puerto Asís',
        'Puerto Caicedo',
        'Puerto Guzmán',
        'Puerto Leguízamo',
        'San Francisco',
        'San Miguel',
        'Santiago',
        'Sibundoy',
        'Valle del Guamuez',
        'Villagarzón'
      ]
    },
    {
      departmentId: 24,
      names: [
        'Armenia',
        'Buenavista',
        'Calarcá',
        'Circasia',
        'Córdoba',
        'Filandia',
        'Génova',
        'La Tebaida',
        'Montenegro',
        'Pijao',
        'Quimbaya',
        'Salento'
      ]
    },
    {
      departmentId: 25,
      names: [
        'Apía',
        'Balboa',
        'Belén de Umbría',
        'Dosquebradas',
        'Guática',
        'La Celia',
        'La Virginia',
        'Marsella',
        'Mistrató',
        'Pereira',
        'Pueblo Rico',
        'Quinchía',
        'Santa Rosa de Cabal',
        'Santuario'
      ]
    },
    { departmentId: 26, names: ['Providencia y Santa Catalina', 'San Andrés'] },
    {
      departmentId: 27,
      names: [
        'Aguada',
        'Albania',
        'Aratoca',
        'Barbosa',
        'Barichara',
        'Barrancabermeja',
        'Betulia',
        'Bolívar',
        'Bucaramanga',
        'Cabrera',
        'California',
        'Capitanejo',
        'Carcasí',
        'Cepitá',
        'Cerrito',
        'Charalá',
        'Charta',
        'Chima',
        'Chipatá',
        'Cimitarra',
        'Concepción',
        'Confines',
        'Contratación',
        'Coromoro',
        'Curití',
        'El Carmen de Chucurí',
        'El Guacamayo',
        'El Peñón',
        'El Playón',
        'Encino',
        'Enciso',
        'Florián',
        'Floridablanca',
        'Galán',
        'Gámbita',
        'Girón',
        'Guaca',
        'Guadalupe',
        'Guapotá',
        'Guavatá',
        'Güepsa',
        'Hato',
        'Jesús María',
        'Jordán',
        'La Belleza',
        'Landázuri',
        'La Paz',
        'Lebrija',
        'Los Santos',
        'Macaravita',
        'Málaga',
        'Matanza',
        'Mogotes',
        'Molagavita',
        'Ocamonte',
        'Oiba',
        'Onzaga',
        'Palmar',
        'Palmas del Socorro',
        'Páramo',
        'Piedecuesta',
        'Pinchote',
        'Puente Nacional',
        'Puerto Parra',
        'Puerto Wilches',
        'Rionegro',
        'Sabana de Torres',
        'San Andrés',
        'San Benito',
        'San Gil',
        'San Joaquín',
        'San José de Miranda',
        'San Miguel',
        'San Vicente de Chucurí',
        'Santa Bárbara',
        'Santa Helena del Opón',
        'Simacota',
        'Socorro',
        'Suaita',
        'Sucre',
        'Suratá',
        'Tona',
        'Valle de San José',
        'Vélez',
        'Vetas',
        'Villanueva',
        'Zapatoca'
      ]
    },
    {
      departmentId: 28,
      names: [
        'Buenavista',
        'Caimito',
        'Chalán',
        'Colosó',
        'Corozal',
        'Coveñas',
        'El Roble',
        'Galeras',
        'Guaranda',
        'La Unión',
        'Los Palmitos',
        'Majagual',
        'Morroa',
        'Ovejas',
        'Palmito',
        'Sampués',
        'San Benito Abad',
        'San Juan de Betulia',
        'San Marcos',
        'San Onofre',
        'San Pedro',
        'Sincelejo',
        'Sucre',
        'Sincé',
        'Tolú',
        'Tolú Viejo'
      ]
    },
    {
      departmentId: 29,
      names: [
        'Alpujarra',
        'Alvarado',
        'Ambalema',
        'Anzoátegui',
        'Armero',
        'Ataco',
        'Cajamarca',
        'Carmen de Apicalá',
        'Casabianca',
        'Chaparral',
        'Coello',
        'Coyaima',
        'Cunday',
        'Dolores',
        'Espinal',
        'Falan',
        'Flandes',
        'Fresno',
        'Guamo',
        'Herveo',
        'Honda',
        'Ibagué',
        'Icononzo',
        'Lérida',
        'Líbano',
        'Mariquita',
        'Melgar',
        'Murillo',
        'Natagaima',
        'Ortega',
        'Palocabildo',
        'Piedras',
        'Planadas',
        'Prado',
        'Purificación',
        'Rioblanco',
        'Roncesvalles',
        'Rovira',
        'Saldaña',
        'San Antonio',
        'San Luis',
        'Santa Isabel',
        'Suárez',
        'Valle de San Juan',
        'Venadillo',
        'Villahermosa',
        'Villarrica'
      ]
    },
    {
      departmentId: 30,
      names: [
        'Alcalá',
        'Andalucía',
        'Ansermanuevo',
        'Argelia',
        'Bolívar',
        'Buenaventura',
        'Buga',
        'Bugalagrande',
        'Caicedonia',
        'Cali',
        'Calima',
        'Candelaria',
        'Cartago',
        'Dagua',
        'El Águila',
        'El Cairo',
        'El Cerrito',
        'El Dovio',
        'Florida',
        'Ginebra',
        'Guacarí',
        'Jamundí',
        'La Cumbre',
        'La Unión',
        'La Victoria',
        'Obando',
        'Palmira',
        'Pradera',
        'Restrepo',
        'Riofrío',
        'Roldanillo',
        'San Pedro',
        'Sevilla',
        'Toro',
        'Trujillo',
        'Tuluá',
        'Ulloa',
        'Versalles',
        'Vijes',
        'Yotoco',
        'Yumbo',
        'Zarzal'
      ]
    },
    { departmentId: 31, names: ['Carurú', 'Mitú', 'Taraira'] },
    { departmentId: 32, names: ['Cumaribo', 'La Primavera', 'Puerto Carreño', 'Santa Rosalía'] }
  ])
  
  const selectedDepartment = ref('')
  const selectedCity = ref('')
  const filteredCities = ref([])
  
  const updateCities = () => {
    const department = cities.value.find(
      (cityGroup) => cityGroup.departmentId === selectedDepartment.value
    )
    filteredCities.value = department ? department.names : []
  }
  
  const getLatLong = (e) => {
    const { lat, lng } = e.latlng
    latitude.value = lat
    longitude.value = lng
  
    if (currentMarker.value) {
      initialMap.value.removeLayer(currentMarker.value)
    }
    currentMarker.value = L.marker([lat, lng]).addTo(initialMap.value)
  }
  
  onMounted(() => {
    initialMap.value = L.map('map').setView([5.0239, -74.0036], 15)
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(initialMap.value)
  
    initialMap.value.on('click', getLatLong)
  })
  </script>
  
  <style>
  @import url(/src/css/forms.sass);
  </style>
  