import { ref } from 'vue'

// Address Information
export const addresses = ref([
    {
        address_id:1,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:2,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },
    {
        address_id:3,
        address_department:"Cundinamarca",
        address_city: "Zipaquira",
        address_name: "Los Olmos",
        address_street: "Cra. 16 #1524",
        address_postal_code: "250251",
        address_lat: "5.0239",
        address_long: "-74.0036",
    },

])
